ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8585
jwt:
  domain: "http://0.0.0.0:8585"
  audience: "jwt-audience"
  realm: "ktor sample app"
  issuer: "http://0.0.0.0:8585"

database:
  userName: "srikantakusubudhi"
  cuserName: "srikanta"
  dbName: "ktor"